# Google Cloud Build Configuration
# Builds Docker images and pushes to Artifact Registry

steps:
  # Step 1: Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/backend:latest'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/backend:${COMMIT_SHA}'
      - './backend'

  # Step 2: Push backend image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/backend:latest'
    waitFor: ['build-backend']

  # Step 3: Build consumer Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-consumer'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/consumer:latest'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/consumer:${COMMIT_SHA}'
      - './consumer'

  # Step 4: Push consumer image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-consumer'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/consumer:latest'
    waitFor: ['build-consumer']

# Images to push to Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/backend:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/consumer:latest'

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'

# Substitution variables
substitutions:
  _REGION: 'europe-southwest1'
  _ARTIFACT_REPO: 'clicker-repo'
